const actionType = {
  SET_IS_PLAY: "SET_IS_PLAY",
  SELECT_DAY: "SELECT_DAY",
  SELECT_COIN: "SELECT_COIN",
  SET_DATA: "SELECT_DATA",
  SET_TRADE_INDEX: "SET_TRADE_INDEX",
  SET_TICKER_INDEX: "SET_TICKER_INDEX",
  SET_ORDERBOOK_INDEX: "SET_ORDERBOOK_INDEX",
  CLICK_MINUTES_BUTTON: "CLICK_MINUTES_BUTTON",
  TIME_LOOP: "TIME_LOOP",
  ERROR_POPUP: "ERROR_POPUP",
};

export default actionType;
